---
#
# Task used to setup some of the parts for LTRSEC-2000 or an internally run lab
#
- name: AWS/Ansible Lab Setup
vars_files:
  vars/users.yaml
  tasks:
    - name: Setup IAM Users
      loop: "{{ vars/users }}"
      ansible.builtin.include_tasks: tasks/setup_iam_users.yaml

...