---
#
# Task used to setup some of the parts for LTRSEC-2000 or an internally run lab
#

- name: AWS Ansible Lab Setup
  hosts: localhost
  gather_facts: yes
  vars_files: 
    - ./vars/main.yml
    - ./vars/users.yml

  tasks:
    - name: Setup IAM Users
      loop: "{{users}}"
      ansible.builtin.include_tasks: tasks/setup_iam_users.yml

...