---
#
# Task used to setup some of the parts for LTRSEC-2000 or an internally run lab
#

- name: AWS Ansible Lab Setup
  hosts: localhost
  gather_facts: yes
  vars_files: 
    - ./vars/main.yml

  tasks:
    - name: Setup IAM Users
      ansible.builtin.include_tasks: tasks/setup_aws_users.yml

    - name: Setup Windows Provisioning Servers
      ansible.builtin.include_tasks: tasks/create_windows_ec2_instances.yml


- name: AWS ASA Lab Setup
  hosts: asa
  gather_facts: no
  vars_files: 
    - ./vars/main.yml

  tasks:
    - name: ASA Show Version
      when: inventory_hostname in groups['asa']
      ansible.builtin.include_tasks: tasks/asa_show_version.yml

    - name: ASA VPN User Update
      when: inventory_hostname in groups['asa']
      ansible.builtin.include_tasks: tasks/asa_create_vpn_users.yml
...