---
#
# Task used to setup some of the parts for LTRSEC-2000 or an internally run lab
#

- name: AWS Ansible Lab Teardown
  hosts: localhost
  gather_facts: yes
  vars_files: 
    - ./vars/main.yml

  tasks:
    - name: List IAM Users
      ansible.builtin.include_tasks: tasks/list_iam_users.yml

    - name: Delete IAM Users
      ansible.builtin.include_tasks: tasks/delete_iam_users.yml

- name: AWS ASA Lab Teardown
  hosts: asa
  gather_facts: no
  vars_files: 
    - ./vars/main.yml
    - ./vars/users.yml

  tasks:
    - name: ASA Show Version
      when: inventory_hostname in groups['asa']
      ansible.builtin.include_tasks: tasks/asa_delete_vpn_users.yml