---
#
# Task used to setup some of the parts for LTRSEC-2000 or an internally run lab
#

- name: Create Azure AD User
  hosts: localhost
  gather_facts: yes
  vars_files: 
    - ./vars/main.yml
  tasks:
    - name: Setup Azure Users
      ansible.builtin.include_tasks: tasks/setup_azure_users.yml
