---
#
# Task to create VPN users or change their passwords (same thing in the cli)
#

- name: Creating VPN Users
  with_sequence: start=0 end={{ NUM_PODS }}
  cisco.asa.asa_config:
    save_when: changed
    lines:
      - username pod{{ item }}-ravpn password {{ lookup('ansible.builtin.env', 'iam_password') }}

- name: Setting User RAVPN attributes
  with_sequence: start=0 end={{ NUM_PODS }}
  cisco.asa.asa_config:
    save_when: changed
    lines:
      - service-type remote-access
    parents: username pod{{ item }}-ravpn attributes

...   