---
#
# Task to show the asa version
#

- name: SHOW VERSION
  cisco.asa.asa_command:
    commands:
      - show version
  register: asa_version

- name: ASA Version
  ansible.builtin.debug:
    msg: "{{asa_version}}"
