---
#
# Task to delete VPN users
#

- name: Deleting VPN Users
  with_sequence: start=0 end={{ NUM_PODS }}
  cisco.asa.asa_config:
    save_when: changed
    lines:
      - no username pod{{ item }}-ravpn attributes
      - no username pod{{ item }}-ravpn

...