---
#
# Create IAM User
#

- name: "Create IAM Users"
  with_sequence: start=0 end={{ NUM_PODS }}
  amazon.aws.iam_user:
    name: "pod{{ item }}-awsadmin"
    state: present
    password: "{{ lookup('ansible.builtin.env', 'iam_password') }}"
    managed_policies:
      - arn:aws:iam::aws:policy/AdministratorAccess
    tags:
      Pod: True

...